<a href="https://colab.research.google.com/github/piocode0110/GoogleColab-Scripts/blob/master/4_OPERACIONES_CON_COLUMNAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas
import os
#VAMOS A EXTRAER DATOS DE UNA PAGINA WEB https://pokemondb.net/pokedex/all  UTILIZANDO  import requests
import requests

In [ ]:
#EXTRAEMOS EL CODIGO
url = "https://pokemondb.net/pokedex/all"
html_text = requests.get(url).content

In [ ]:
 #CREAMOS UN DATAFREAM
contenido = pandas.read_html(html_text)

In [ ]:
# extraemos los datos
df_pokedex = contenido[0]

In [ ]:
df_pokedex

        #                    Name           Type  ...  Sp. Atk  Sp. Def  Speed
0       1               Bulbasaur   Grass Poison  ...       65       65     45
1       2                 Ivysaur   Grass Poison  ...       80       80     60
2       3                Venusaur   Grass Poison  ...      100      100     80
3       3  Venusaur Mega Venusaur   Grass Poison  ...      122      120     80
4       4              Charmander           Fire  ...       60       50     65
...   ...                     ...            ...  ...      ...      ...    ...
1040  896               Glastrier            Ice  ...       65      110     30
1041  897               Spectrier          Ghost  ...      145       80    130
1042  898                 Calyrex  Psychic Grass  ...       80       80     80
1043  898       Calyrex Ice Rider    Psychic Ice  ...       85      130     50
1044  898    Calyrex Shadow Rider  Psychic Ghost  ...      165      100    150

[1045 rows x 10 columns]

In [ ]:
df_pokedex.head()

   #                    Name          Type  ...  Sp. Atk  Sp. Def  Speed
0  1               Bulbasaur  Grass Poison  ...       65       65     45
1  2                 Ivysaur  Grass Poison  ...       80       80     60
2  3                Venusaur  Grass Poison  ...      100      100     80
3  3  Venusaur Mega Venusaur  Grass Poison  ...      122      120     80
4  4              Charmander          Fire  ...       60       50     65

[5 rows x 10 columns]

In [ ]:
#VAMOS A SUMAR LA COLUMNAS DE ATAQUE Y ATAQUE ESPECIAL CON EL SIGUIENTE COMANDO
df_pokedex["Attack"] + df_pokedex["Sp. Atk"]

0       114
1       142
2       182
3       222
4       112
       ...
1040    210
1041    210
1042    160
1043    250
1044    250
Length: 1045, dtype: int64

In [ ]:
#PARA ASIGNARLOS A UNA NUEVA COLUMNA (TOTAL_ataque)
df_pokedex["Total_ataque"] =  df_pokedex["Attack"] + df_pokedex["Sp. Atk"]

In [ ]:
df_pokedex

        #                    Name           Type  ...  Sp. Def  Speed  Total_ataque
0       1               Bulbasaur   Grass Poison  ...       65     45           114
1       2                 Ivysaur   Grass Poison  ...       80     60           142
2       3                Venusaur   Grass Poison  ...      100     80           182
3       3  Venusaur Mega Venusaur   Grass Poison  ...      120     80           222
4       4              Charmander           Fire  ...       50     65           112
...   ...                     ...            ...  ...      ...    ...           ...
1040  896               Glastrier            Ice  ...      110     30           210
1041  897               Spectrier          Ghost  ...       80    130           210
1042  898                 Calyrex  Psychic Grass  ...       80     80           160
1043  898       Calyrex Ice Rider    Psychic Ice  ...      130     50           250
1044  898    Calyrex Shadow Rider  Psychic Ghost  ...      100    150           250

[1045 rows x 11 columns]

In [ ]:
#PARA SUMAR TODAS LAS COLUMNAS DE LA TABLA
df_pokedex.get(["HP", "Attack","Defense", "Sp. Atk", "Sp. Def", "Speed"]).sum(axis = 1)

0       318
1       405
2       525
3       625
4       309
       ...
1040    580
1041    580
1042    500
1043    680
1044    680
Length: 1045, dtype: int64

In [ ]:
#PARA ASIGNARLOS A UNA NUEVA COLUMNA 
df_pokedex["Total_ Estadistica"] = df_pokedex.get(["HP", "Attack","Defense", "Sp. Atk", "Sp. Def", "Speed"]).sum(axis = 1)

In [ ]:
df_pokedex

        #                    Name  ... Total_ataque  Total_ Estadistica
0       1               Bulbasaur  ...          114                 318
1       2                 Ivysaur  ...          142                 405
2       3                Venusaur  ...          182                 525
3       3  Venusaur Mega Venusaur  ...          222                 625
4       4              Charmander  ...          112                 309
...   ...                     ...  ...          ...                 ...
1040  896               Glastrier  ...          210                 580
1041  897               Spectrier  ...          210                 580
1042  898                 Calyrex  ...          160                 500
1043  898       Calyrex Ice Rider  ...          250                 680
1044  898    Calyrex Shadow Rider  ...          250                 680

[1045 rows x 12 columns]